### ISSUE TITLE
Transloco @ngneat/transloco@6.0.4 deprecated 

### ISSUE THREAD

**Issue by ClaubercyKloss** [iatecbr/IATec.Standard.WebUI.Angular#1]
No template  está sendo usado o @ngneat/transloco@6.0.4, mas está deprecado. 
 
npm warn deprecated @ngneat/transloco@6.0.4: NOTICE: Transloco has moved to a new scope, this package will no longer receive updates. please use @jsverse/transloco instead.
 
 
Precisa ser atualizado para a versão @jsverse/transloco:
"@jsverse/transloco": "^7.4.3"

**Comment by elvysmarcos** [comment]
Atualizado a dependência na versão 3.3.0 do Nephos Layout

**Comment by elvysmarcos** [comment]
Atualizado a dependência na versão 3.3.0 do Nephos Layout
